### ISSUE TITLE
IllegalStateException: Zip File Closed

### ISSUE THREAD

**Issue by TakaoDev** [discord-jda/JDA#2486] opened 2023-06-25 14:08 UTC
### General Troubleshooting

- [ ] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

I made JDA bot send a message to a channel, and it's doing it but i'm getting this weird error message in my console: 
```
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:42) ~[?:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1014) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:900) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:878) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1053) ~[?:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
```

### Code Example for Reproduction Steps

```java
@EventHandler
    public void onChat(AsyncPlayerChatEvent e){
        if(e.getMessage().startsWith("#")) return;

        System.out.println("WORKING!");

        TextChannel channel = TWDiscordIntegration.getInstance().getBot().getTextChannelById("1122502390642380861");
        channel.sendMessage(e.getPlayer().getDisplayName() + "> " + e.getMessage()).queue();

    }
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDA bot = JDABuilder.createDefault("here is my token").setActivity(Activity.playing("su TogetherWorld!")).build();
        loadListeners();
```

### Exception or Error

```yesyes
java.lang.IllegalStateException: zip file closed
```

**Comment by freya022** [comment] 2023-06-25 14:10
Duplicate of https://github.com/discord-jda/JDA/issues/1429 https://github.com/discord-jda/JDA/issues/1440 https://github.com/discord-jda/JDA/issues/1761 https://github.com/discord-jda/JDA/issues/1771 https://github.com/discord-jda/JDA/issues/1780 https://github.com/discord-jda/JDA/issues/1861 https://github.com/discord-jda/JDA/issues/2197 https://github.com/discord-jda/JDA/issues/2217 https://github.com/discord-jda/JDA/issues/2303

See also https://jda.wiki/using-jda/troubleshooting/#illegalstateexception-zip-file-closed

**Closed** 2023-06-25 14:10 UTC
