### ISSUE TITLE
JDA hangs with JDK17 on a single core x64 Linux machine

### ISSUE THREAD

**Issue by mbarkley** [discord-jda/JDA#1858] opened 2021-10-05 03:53 UTC
## Bug Report
When using JDA `4.3.0_331` with JDK17 on a single core Linux machine, JDA is unable to login to Discord.

### Expected Behavior
Should be able to login to Discord and not hang.

### Code Example or Reproduction Steps

To reproduce, follow these steps on an x64 Linux machine (I reproduced on Ubuntu 18.04 and 20.04):
1. Clone [this bot](https://github.com/mbarkley/modus-rollens)
2. [Download and extract JDK17](https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_linux-x64_bin.tar.gz)
3. Build the bot with `mvn package`
4. Configure a Discord token with `export DISCORD_TOKEN=<TOKEN_HERE>`
5. Run the jar with Java 17 and a single core:
   ```
    taskset --cpu-list 1 java -jar target/modus-rollens-1.0-SNAPSHOT.jar
    ```

### Workaround
You can bypass this issue by explicitly setting the fork join pool parallelism on startup:
```
 taskset --cpu-list 1 java -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -jar target/modus-rollens-1.0-SNAPSHOT.jar
```

**Comment by Tais993** [comment] 2021-10-05 05:05
https://bugs.openjdk.java.net/browse/JDK-8274349?focusedCommentId=14450437&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14450437

Got noticed by another bot developer too, not JDA's fault

**Comment by SirYwell** [comment] 2022-01-26 13:39
The issue is resolved in Java 17.0.2 which was released on January 18th.

**Comment by Taz03** [comment] 2022-10-07 21:03
close this then?

**Comment by MinnDevelopment** [comment] 2024-01-21 09:41
Closing this, since the JDK bug has been fixed 2 years ago.

**Closed by MinnDevelopment** 2024-01-21 09:41 UTC
Labels: type: jre issue
